### ISSUE TITLE
Add orientation

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#43]
We need to offer the possibility to "flip" regions that are on the negative strand.

This should probably be done at the `mg$matrix` level.

Possibility to add a `flip_regions` function?

**Comment by CharlesJB** [comment]
## TODO
- [ ] Create a `flip_regions` public function (see below for description).
- [ ] Create an `unflip_regions` public function.
- [ ] Add a `flip_regions` parameter to the `self$plot` function.
- [ ] Update the documentation (ROxygen comments and man page).
- [ ] Add unit tests.

## `flip_regions` description:
* Must check if the are matrices in `self$matrix`. If not, do nothing.
* Must check if regions are already flipped, with the `self$params[["flipped"]]` value. By default, the value is not in the `self$params` list so it should be added when the `flip_regions` function is first called. When an item is absent from a list, looking for it will return `NULL` (i.e.: `is.null(self$params[["flipped"]])` is `TRUE` before `flipped` is defined). 
* `self$matrix` is a list of lists of lists. The first level is the name of the region used (corresponding to the names of `self$regions`. The second levels contain the design names (the columns names of the design). The third levels have 1 or 2 values. The first that is always present is `[["input"]]` and a second that is not always present is `[["ctrl"]]`.
* See [metagene.R](https://github.com/CharlesJB/metagene/blob/master/R/metagene.R#L193) for an example on how to loop through the levels of `self$matrix`. Use `names(self$regions)` instead of `select_regions`. The design can be accessed with `self$design`.
* For each regions, we need to flip the rows corresponding to regions on the negative strand (`-`) in the corresponding matrices.
* After flipping the region, we must set `self$params[["flipped"]]` to TRUE.
* The function must return the current object (i.e.:  the last line must be: `invisible(self)`).

## Avoiding code duplication

* To avoid code duplication while making sure the object remains in a valid state, the actual flipping should be done by a private function that don't check for the `self$params[["flipped"]]`.
* This function can then be used for the `flip_regions` and `unflip_regions` functions.
* The check of the `self$params[["flipped"]]` is done by the public functions and the private function is called only if needed.
