### ISSUE TITLE
Beautifulize heatmaps

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#44]
## General idea

* Right now the heatmaps are produced with a call of the `heatmap.2` function with basic parameters. The result is a heatmap with squares that is not very compact.
* The current version can also manage only 1 sample at a time. It would be better to be able to give a list of samples to include (not unlike the `self$plot` function).
* If possible, it should be able to produce something looking similar to the panel b in this [figure](http://www.nature.com/ncb/journal/v14/n7/fig_tab/ncb2520_F4.html).
* In the best case scenario, each "columns" would correspond to a file, or a design group, and each group of regions would be slightly separated from the others.
* For instance, in the following sketch, there would be 2 files to include in the heatmaps (F1 and F2) and 3 groups of regions (R1, R2 and R3).

```
           F1        F2
       ---------  ---------
  R1  |         ||         |
      |         ||         |
       ---------  ---------
  R2  |         ||         |
      |         ||         |
       ---------  ---------
  R3  |         ||         |
      |         ||         |
       ---------  ---------
```

## Specifics

* The basis of the function are similar to the [`self$plot`](https://github.com/CharlesJB/metagene/blob/master/R/metagene.R#L217) function.
  * All the params would be the same, except for `range` that should not be included.
  * Everything before the [second step (#2)](https://github.com/CharlesJB/metagene/blob/master/R/metagene.R#L220-L223) should be the same.
  * The looping through the matrices should be similar to what is done in the [`self$plot`](https://github.com/CharlesJB/metagene/blob/master/R/metagene.R#L230-L231) function

**Comment by CharlesJB** [comment]
## TODO

- [ ] Find the correct params for the `heatmap.2` call to produce a more compact heatmap representation (see the General Idea section of previous post).
- [ ] Add a multi-sample management similar to what is implemented in the `self$plot` function (see the Specifics section of previous post).
- [ ] Update the documentation accordingly:
  - [ ] ROxygen
  - [ ] Man pages
- [ ] Add an example in the vignette.
- [ ] Add some unit tests to check invalid params values.

**Comment by CharlesJB** [comment]
We will use the [Imetagene](https://github.com/andronekomimi/Imetagene) package to show heatmaps.
