### ISSUE TITLE
Update the available regions datasets

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#45]
Currently, we have `TSS.human` and `TSS.mouse` in [`inst/extdata`](https://github.com/CharlesJB/metagene/tree/master/inst/extdata).

They should be removed for the following reasons:
* They were generated with the [`getGenesBiomart`](https://github.com/CharlesJB/metagene/blob/master/R/Utilities.R#L75-L123) function.
  * The regions obtained this way are not clearly associated with a genome version and thus are more complicate to replicate.
  * The [`Txdb`](http://bioconductor.org/packages/release/BiocViews.html#___TxDb) brand of packages would be a better choice.
* They were generate with an old version of `GenomicRanges` and should minimally be updated.

Also, the [`getGenes`](https://github.com/CharlesJB/metagene/blob/master/R/Utilities.R#L46) function should also be removed if the dataset are in the `data` folder to be accessed directly.

**Comment by CharlesJB** [comment]
The GRanges can easily be generated using a `TxDb` object:
```
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
promoters.hg19 <- promoters(genes(TxDb.Hsapiens.UCSC.hg19.knownGene), 1000, 1000)
```

**Comment by CharlesJB** [comment]
## TODO

- [ ] Replace the [`getGenesBiomart`](https://github.com/CharlesJB/metagene/blob/master/R/Utilities.R#L86) function by a `get_promoters_txdb` function.
- [ ] Generate basic datasets (should be saved in `data` instead of `inst/extdata`):
  - [ ] mm9
  - [ ] mm10
  - [ ] hg18
  - [ ] hg19
- [ ] Add the documentation for each dataset (ROxygen comments and man pages):
  - [ ] mm9
  - [ ] mm10
  - [ ] hg18
  - [ ] hg19
- [ ] Remove the old datasets (`TSS.human` and `TSS.mouse`)
- [ ] Add a small section in the vignette.
