### ISSUE TITLE
Disable Friedman test by default

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#53]
Add a parameter to define if Friedman test result should be shown on the graph.

# TODO:
- [x] Add a `show_friedman` argument to the `plot` function with a default of `FALSE`
- [x] Add a check for the value before doing the Friedman's test
- [x] Update the documentation
- [x] Add unit tests
- [x] R CMD check
- [x] R CMD BiocCheck
