### ISSUE TITLE
produce_matrices should be an independent step

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#54]
The `produce_matrices` should no longer be performed by the `plot` function. While this will add an extra step compared to the previous version of the analysis, it will make each step performed by metagene much clearer.

# TODO:
- [x] Remove `produce_matrices` function call from `plot`.
- [x] Remove the arguments specific to `produce_matrices` from the `plot` list of arguments.
- [x] Update the documentation (ROxygen and man pages)
- [x] Update Unit tests
- [x] Update vignette (`Analysis steps` section).
- [x] R CMD check
- [x] R CMD BiocCheck
