### ISSUE TITLE
Add getters

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#56]
There are still a few members of metagene that are [public](https://github.com/CharlesJB/metagene/blob/2.2.0/R/metagene.R#L157-L162):
* `params`
* `regions`
* `matrices`
* `design`

We need to make them private and add getters function instead.

# TODO:
- [x] Make members private
- [x] Convert all self$\<member\> to private$\<member\>
- [x] Add getters functions
- [x] Convert all mg$\<member\> to mg$\<getter\> 
- [x] Update documentation (ROxygen and man pages)
- [x] Add a section in vignette
- [x] Update unit tests
- [ ] R CMD check
- [ ] R CMD BiocCheck
