### ISSUE TITLE
Add a produce_data_frame function

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#57]
We need to add a public function named `produce_data_frame` that will create the `data.frame` that will be the input of the `ggplot` call in the [`plot`](https://github.com/CharlesJB/metagene/blob/2.2.0/R/metagene.R#L298-L375) function of metagene.

This should simplify the [`plot`](https://github.com/CharlesJB/metagene/blob/2.2.0/R/metagene.R#L298-L375) function.

The `produce_data_frame` function should keep track of the params used in previous call to avoid recreating the `data.frame` for nothing.

The result of the function should be a single `data.frame` saved as `private$df`. The filtering of regions and experiment name should be done by the [`plot`](https://github.com/CharlesJB/metagene/blob/2.2.0/R/metagene.R#L298-L375).

# TODO:
- [x] Create the `produce_data_frame` public function.
- [x] Use it in the `plot` function.
- [x] Add a `get_data_frame` function.
- [x] Add a `get_plot` function.
- [x] Update the documentation ROxygen and man pages.
- [x] Add Unit tests.
- [x] R CMD check.
- [x] R CMD BiocCheck
