### ISSUE TITLE
Refactor bootstrap

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#61]
# Problematic

In the current implementation, the parallelization is done when [the replicate values are calculated](https://github.com/CharlesJB/metagene/blob/master/R/stats.R#L261-L262). This was initially done to avoid using too much memory.

It is no longer clear if the is really an improvement in the memory usage since the whole environment appears to be copied when the R process is forked during the parallelization.

But most importantly, the process forking is considerably slowing the computations since a new R environment is created every time.

# Solution:

I need to put the parallelization at the `regions` / `bam_files` level. I will create a `list` of `character` vector that represent all the possible combination of `regions` and `bam_files`. Each vector of the `list` will contains the name of the region and the name of the bam file in 2 separate positions. This `list` is then used with the `parallel_job` object.

The [`stats`](https://github.com/CharlesJB/metagene/blob/master/R/stats.R) should no longer use parallelization.

# TODO:
- [x] Refactor the [`stats`](https://github.com/CharlesJB/metagene/blob/master/R/stats.R) to remove the `parallel_job`.
- [x] Create the function that uses the elements of the `list`.
- [x] Generate all the combinations of regions and bam files.
- [x] Launch the parallel computation from the `metagene` object.
- [x] Update unit tests.
