### ISSUE TITLE
binSize always 1

### ISSUE THREAD

**Issue by CharlesJB** [CharlesJB/metagene#62]
In the [`metagene$plot` function](https://github.com/CharlesJB/metagene/blob/master/R/metagene.R#L467-L504), the `binSize` argument is always one [when calling `plot_graphics`](https://github.com/CharlesJB/metagene/blob/master/R/metagene.R#L499-L500).

I need to fetch the `private$params$binSize` value and use it before the call.

# TODO:
- [ ] Correct the code.
- [ ] Add unit tests.
- [ ] Update devel branch.

**Comment by CharlesJB** [comment]
Should be solved by d180f98421085321adef6cd48a66178428dffba9.
